version: '3.8'

services:
  llama:
    image: llama-model-image:3.2  # Llama 3.2의 Docker 이미지를 지정
    container_name: llama_3.2
    ports:
      - "8000:8000"  # 외부에서 접근할 포트를 설정
    environment:
      - MODEL_PATH=/path/to/llama/model  # Llama 모델의 경로
      - API_PORT=8000
    volumes:
      - /local/path/to/llama:/path/to/llama/model  # 모델 파일을 컨테이너에 마운트
    command: ["start-llama", "--api-port", "8000"]  # Llama 서버 시작 명령어